import React, { useState } from 'react';
import { Download, Edit3, Save, FileCheck, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import EditFieldModal from './EditFieldModal';
import { toast } from 'sonner';
import { generateLegalDocx } from '@/lib/docx-generator';
import { useParams } from 'react-router-dom';

interface ReviewSectionProps {
  initialResult: any;
  onFinalize: (finalData: any) => void;
}

const ReviewSection: React.FC<ReviewSectionProps> = ({ initialResult, onFinalize }) => {
  const { moduleId } = useParams<{ moduleId: string }>();
  const [data, setData] = useState(initialResult);
  const [editingField, setEditingField] = useState<{ name: string; value: string } | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = async () => {
    if (!moduleId) return;
    
    setIsDownloading(true);
    try {
      const blob = await generateLegalDocx(moduleId as any, data, data.language || 'en');
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Murdock_${moduleId}_${new Date().getTime()}.docx`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('Professional Legal Draft Downloaded');
    } catch (error) {
      console.error('DOCX Error:', error);
      toast.error('Failed to generate document');
    } finally {
      setIsDownloading(false);
    }
  };

  const handleEditClick = (fieldName: string, value: string) => {
    setEditingField({ name: fieldName, value });
  };

  const handleSaveField = (newValue: string) => {
    if (editingField) {
      setData({ ...data, [editingField.name]: newValue });
      setEditingField(null);
      toast.success('Field updated locally');
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-display font-bold text-text-primary">Review & Refine</h2>
          <p className="text-sm text-text-muted">Fields highlighted in <span className="text-gold font-bold">gold</span> were generated by AI. Verify them carefully.</p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" className="border-border-default text-text-primary">
            <Share2 className="w-4 h-4 mr-2" /> Share
          </Button>
          <Button 
            onClick={handleDownload} 
            disabled={isDownloading}
            className="bg-gold hover:bg-gold-light text-background font-bold"
          >
            {isDownloading ? (
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-background border-t-transparent mr-2" />
            ) : (
              <Download className="w-4 h-4 mr-2" />
            )}
            Download .DOCX
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <Card className="bg-white text-gray-900 shadow-xl border-0 min-h-[842px] p-12 font-serif overflow-hidden relative">
             <div className="absolute top-0 right-0 p-4 opacity-10">
               <FileCheck className="w-24 h-24 text-gray-900" />
             </div>
             
             <div className="space-y-6 relative z-10">
                {/* Mockups of the document structure */}
                <div className="text-center font-bold text-xl uppercase underline mb-8">
                   Draft Document
                </div>

                {Object.entries(data).map(([key, value]) => {
                  const isAI = [
                    'defect_description', 
                    'relief_sought', 
                    'facts_of_case', 
                    'legal_grounds', 
                    'demand', 
                    'narrative', 
                    'information_sought',
                    'grievance_narrative',
                    'dispute_summary',
                    'fraud_details',
                    'remedy_sought'
                  ].includes(key);
                  
                  return (
                    <div key={key} className="group relative">
                      <div 
                        onClick={() => isAI && handleEditClick(key, value as string)}
                        className={`p-2 rounded transition-all cursor-pointer ${
                          isAI 
                          ? 'bg-gold/10 border-l-2 border-gold hover:bg-gold/20' 
                          : 'hover:bg-gray-50'
                        }`}
                      >
                         <span className="text-[10px] uppercase tracking-widest text-gray-400 font-bold block mb-1">
                           {key.replace(/_/g, ' ')}
                         </span>
                         <p className="text-[15px] leading-relaxed text-gray-800 whitespace-pre-wrap">
                           {value as string}
                         </p>
                         {isAI && (
                           <div className="absolute right-2 top-2 opacity-0 group-hover:opacity-100 transition-opacity">
                             <Edit3 className="w-4 h-4 text-gold" />
                           </div>
                         )}
                      </div>
                    </div>
                  );
                })}
             </div>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="bg-bg-card border-border-default border-t-2 border-t-gold">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 text-gold">
                <SparklesIcon className="w-5 h-5" />
                <h3 className="font-bold">AI Suggestions</h3>
              </div>
              <p className="text-xs text-text-secondary leading-relaxed">
                The generated text follows standard legal terminology for your selected module. 
                Ensure names, dates, and specifically the "Facts" sections reflect your situation accurately.
              </p>
              <div className="pt-4 border-t border-border-default flex flex-col gap-2">
                 <Button variant="ghost" className="w-full justify-start text-xs text-text-muted hover:text-gold hover:bg-gold/5">
                   Regenerate Facts Section
                 </Button>
                 <Button variant="ghost" className="w-full justify-start text-xs text-text-muted hover:text-gold hover:bg-gold/5">
                   Make Tone More Formal
                 </Button>
              </div>
            </CardContent>
          </Card>

          <div className="rounded-xl p-5 bg-sage/5 border border-sage/20 space-y-3">
             <div className="flex items-center gap-2 text-sage">
                <FileCheck className="w-4 h-4" />
                <span className="text-xs font-bold uppercase tracking-widest">Compliance Check</span>
             </div>
             <p className="text-[11px] text-text-secondary italic">
               Document matches CP Act 2019 procedural guidelines. Verified by Murdock legal-core 1.0.
             </p>
          </div>
        </div>
      </div>

      {editingField && (
        <EditFieldModal
          isOpen={!!editingField}
          onClose={() => setEditingField(null)}
          fieldName={editingField.name}
          fieldValue={editingField.value}
          onSave={handleSaveField}
        />
      )}
    </div>
  );
};

const SparklesIcon = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 3l1.912 5.813a2 2 0 001.275 1.275L21 12l-5.813 1.912a2 2 0 00-1.275 1.275L12 21l-1.912-5.813a2 2 0 00-1.275-1.275L3 12l5.813-1.912a2 2 0 001.275-1.275L12 3z" />
    <path d="M5 3l1 1" /><path d="M19 3l-1 1" /><path d="M5 21l1-1" /><path d="M19 21l-1-1" />
  </svg>
);

export default ReviewSection;
